import Head from 'next/head'
import Img from '../components/home/Img'
import IntroHm from '../components/home/IntroHm'
import TextDX from '../components/home/TextDX'
import {motion, useScroll, useTransform, useSpring} from 'framer-motion'
import Homesec from '../components/home/Homesec'
import Footer from '../components/Footer'


export default function Home() {

  const { scrollYProgress } = useScroll();
  const spScroll = useSpring(scrollYProgress, { stiffness: 500, damping: 100 })
  const y = useTransform(spScroll, [0, .3], [100, 0])

  return (
    <div>
      <Head>
        <title>Park Eun Sun</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex'>

          <div className='z-[0]'>
            <IntroHm/>
            <Img url={'https://parkeunsunbucket.s3.eu-west-3.amazonaws.com/Images/Home/DSC_2.png'}/>
          </div>

          <div className='absolute right-5 md:right-10 mt-[20vh] md:mt-[50vh] md:mr-[2vw] z-10'>
            {/* <div className='flex md:h-auto'>
              <motion.img style={{ y }} src='/media/Home/EUN_SUN_PARK-38.jpg' className='absolute md:h-[70vh] -z-10 rounded-md shadow-xl'/>
            </div> */}
            <TextDX/>
          </div>

          <div className='md:mt-[175vh] mt-[100vh] z-[20]'>
            <Homesec/>
          </div>



      </div>
      <div className='absolute'>
          <Footer/>
      </div>
      <div className='absolute right-32 opacity-0 md:opacity-100'>
          <div className='text-[28px] md:m-14'>Follow me on Instagram <a className='text-[30px] text-gray-600 hover:text-lime-700 text-  hover:cursor-pointer'>Parkeunsun.Sculptor</a></div>
      </div>

      

    </div>
  )
}
